---
trigger:

  # Already default, but made explicit here
  branches:
    include: ["*"]

  # Ensure Azure triggers a build on a new tag
  # We use these for GitHub releases
  tags:
    include: ['*']

  paths:
    # Do not trigger a build on changes at these paths
    exclude:
      - docs/*
      - .gitignore
      - LICENSE.txt
      - README.md


jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python37:
          python.version: '3.7'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
      - powershell: |
          pip install --upgrade pip
          pip install .
        displayName: 'pip install'
