---
site_name: Allspark
site_description: The supreme application launcher
site_author: mottosso
site_url: https://allspark.sh

# Repository
repo_name: mottosso/allspark
repo_url: https://github.com/mottosso/allspark

copyright: "Copyright &copy; 2019 mottosso"

# Page tree
nav:
  - Home: index.md
  - Guides: guides.md

docs_dir: pages

theme:
  name: material
  logo: logo.png
  custom_dir: theme
  palette:
    primary: "white"
    accent: "white"

extra_css:
  - extra.css
  # Landing page includes additional CSS from landing.html

# Options
extra:
  feature:
    tabs: true

markdown_extensions:
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde